name: Lint

on:
  - pull_request
  - push

jobs:
  super-linter:
    name: Run Super-Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Run Super-Linter
        uses: github/super-linter@v4.6.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_GO: false # Go linting is broken for now, see: https://github.com/github/super-linter/issues/143
          VALIDATE_JSCPD: false # TODO(dfurman): consider configuring this linter

  golangci-lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: v1.39
